# Generated by Django 5.2 on 2025-05-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product')),
                ('price', models.PositiveIntegerField(verbose_name='Product price')),
                ('name', models.CharField(max_length=100, verbose_name='Product name')),
            ],
        ),
    ]
