# Generated by Django 5.2 on 2025-05-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='barnd_product')),
                ('price', models.PositiveIntegerField(verbose_name='Brand_Product price')),
                ('name', models.CharField(max_length=100, verbose_name='Brand_Product name')),
            ],
        ),
    ]
