# Generated by Django 5.2 on 2025-05-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_brand_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Contact name')),
                ('email', models.EmailField(max_length=254, verbose_name='Contact email')),
                ('phone', models.CharField(max_length=60, verbose_name='Contact phone')),
                ('message', models.TextField(verbose_name='Contact message')),
            ],
        ),
    ]
